trigger:
  - main

pool:
  vmImage: "windows-latest" # Use Windows for .NET + Playwright + Browser

variables:
  DOTNET_VERSION: "8.0.x"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: "$(DOTNET_VERSION)"

  - script: |
      dotnet restore
      dotnet build --no-restore
    displayName: "Restore and Build Solution"

  - script: |
      dotnet publish BlazorApp1/BlazorApp1.csproj -c Release -o publish
    displayName: "Publish Blazor App"

  - script: |
      dotnet tool install --global Microsoft.Playwright.CLI
      playwright install
    displayName: "Install Playwright Browsers"

  - script: |
      dotnet run --project BlazorApp1/BlazorApp1.csproj --urls http://localhost:5292 &
      Start-Sleep -Seconds 10
      dotnet test PlaywrightTests/PlaywrightTests.csproj --no-build
    displayName: "Run Playwright Tests"
